name: Formatters & Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: --enable-preview --add-modules jdk.incubator.concurrent
    steps:
      - name: Checkout project (pull-request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout project (main)
        if: github.event_name == 'push'
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Run checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt ci-test
      - name: Run integration checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt ci-it-test
