name: Release

on:
  release:
    types: [published]
  push:
    branches: [main]
		tags: ["*"]

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: --enable-preview --add-modules jdk.incubator.concurrent
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Scala
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Release new version
        run: sbt ci-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.XEB_SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.XEB_SONATYPE_USERNAME }}